
strictPeerDependencies: true
dedupePeerDependents: true
nodeLinker: isolated

packages:
  - "apps/*"
  - "libs/**"
  - "infra/**"
  - "tools/**"
  - "turbo/**"
  - "!**/vite/types/**"
  - "!**/node_modules/**"
