
strictPeerDependencies: true
dedupePeerDependents: true
nodeLinker: isolated
onlyBuiltDependencies:
  - "@swc/core"
  - "esbuild"
  - "protobufjs"

packages:
  - "apps/*"
  - "libs/**"
  - "infra/**"
  - "tools/**"
  - "turbo/**"
  - "!**/vite/types/**"
  - "!**/node_modules/**"
