const MS_PER_DAY = 24 * 60 * 60 * 1000;

export const JIRA_WEBHOOK_RENEWAL_THRESHOLD_MS = 7 * MS_PER_DAY;
export const JIRA_WEBHOOK_RENEWAL_SWEEP_BATCH_SIZE = 20;
export const JIRA_REFRESH_TOKEN_IDLE_WINDOW_MS = 90 * MS_PER_DAY;
export const JIRA_REFRESH_TOKEN_REFRESH_LEAD_TIME_MS = 14 * MS_PER_DAY;
export const JIRA_REFRESH_TOKEN_PROACTIVE_REFRESH_AFTER_MS =
  JIRA_REFRESH_TOKEN_IDLE_WINDOW_MS - JIRA_REFRESH_TOKEN_REFRESH_LEAD_TIME_MS;
export const JIRA_REFRESH_TOKEN_SWEEP_BATCH_SIZE = 20;
export const JIRA_MAINTENANCE_TASK_QUEUE = 'integrations-jira-maintenance';
